## EDA on Flight Price Dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

df=pd.read_excel(r"C:\Users\Devendra\Downloads\flight_price.xlsx")
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [2]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [3]:
df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [4]:
#getting info about data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [5]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [6]:
from sklearn.preprocessing import OneHotEncoder
o_encoder=OneHotEncoder()
o_encoded=o_encoder.fit_transform(df[['Airline','Source','Destination']]).toarray()
encoded_df=pd.DataFrame(o_encoded,columns=o_encoder.get_feature_names_out())
df.drop(['Airline','Source','Destination'],axis=1,inplace=True)

In [7]:
df=pd.concat([df,encoded_df],axis=1)
df

,Date_of_Journey,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Airline_Air Asia,Airline_Air India,...,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,24/03/2019,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1/05/2019,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,9/06/2019,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,12/05/2019,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,01/03/2019,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,9/04/2019,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,1.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10679,27/04/2019,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10680,27/04/2019,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10681,01/03/2019,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10682,9/05/2019,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [8]:
df.head()

,Date_of_Journey,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Airline_Air Asia,Airline_Air India,...,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,24/03/2019,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1/05/2019,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,9/06/2019,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,12/05/2019,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,01/03/2019,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [9]:
#Featuring date of journey
df['Date']=df['Date_of_Journey'].str.split('/').str[0]
df['Month']=df['Date_of_Journey'].str.split('/').str[1]
df['Year']=df['Date_of_Journey'].str.split('/').str[2]

In [10]:
df.head(2)
df.drop('Date_of_Journey',axis=1,inplace=True)
df

,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Airline_Air Asia,Airline_Air India,Airline_GoAir,...,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,Date,Month,Year
0,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,24,03,2019
1,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1,05,2019
2,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,9,06,2019
3,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,12,05,2019
4,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,01,03,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,9,04,2019
10679,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,27,04,2019
10680,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,27,04,2019
10681,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,01,03,2019
10682,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,9,05,2019

In [11]:
df.head(2)

,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Airline_Air Asia,Airline_Air India,Airline_GoAir,...,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,Date,Month,Year
0,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,24,03,2019
1,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1,05,2019

In [12]:
df.drop('Route',axis=1,inplace=True)

In [13]:
df.head()

,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Airline_Air Asia,Airline_Air India,Airline_GoAir,Airline_IndiGo,...,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,Date,Month,Year
0,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,24,03,2019
1,05:50,13:15,7h 25m,2 stops,No info,7662,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1,05,2019
2,09:25,04:25 10 Jun,19h,2 stops,No info,13882,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,9,06,2019
3,18:05,23:30,5h 25m,1 stop,No info,6218,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,12,05,2019
4,16:50,21:35,4h 45m,1 stop,No info,13302,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,01,03,2019

In [14]:
df['Dep_Hour']=df['Dep_Time'].str.split(':').str[0]
df['Dep_Min']=df['Dep_Time'].str.split(':').str[1]
df.drop('Dep_Time',axis=1,inplace=True)
df

,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Airline_Air Asia,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,...,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,Date,Month,Year,Dep_Hour,Dep_Min
0,01:10 22 Mar,2h 50m,non-stop,No info,3897,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,24,03,2019,22,20
1,13:15,7h 25m,2 stops,No info,7662,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1,05,2019,05,50
2,04:25 10 Jun,19h,2 stops,No info,13882,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,9,06,2019,09,25
3,23:30,5h 25m,1 stop,No info,6218,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,12,05,2019,18,05
4,21:35,4h 45m,1 stop,No info,13302,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,01,03,2019,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,22:25,2h 30m,non-stop,No info,4107,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,9,04,2019,19,55
10679,23:20,2h 35m,non-stop,No info,4145,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,27,04,2019,20,45
10680,11:20,3h,non-stop,No info,7229,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,27,04,2019,08,20
10681,14:10,2h 40m,non-stop,No info,12648,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,01,03,2019,11,30
10682,19:15,8h 20m,2 stops,No info,11753,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,9,05,2019,10,55

In [15]:
df['Arr_Hour']=df['Arrival_Time'].str.split(' ').str[0].str.split(':').str[0]
df['Arr_Min']=df['Arrival_Time'].str.split(' ').str[0].str.split(':').str[1]
df.drop('Arrival_Time',axis=1,inplace=True)
df

,Duration,Total_Stops,Additional_Info,Price,Airline_Air Asia,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,...,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,Date,Month,Year,Dep_Hour,Dep_Min,Arr_Hour,Arr_Min
0,2h 50m,non-stop,No info,3897,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,24,03,2019,22,20,01,10
1,7h 25m,2 stops,No info,7662,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1,05,2019,05,50,13,15
2,19h,2 stops,No info,13882,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,9,06,2019,09,25,04,25
3,5h 25m,1 stop,No info,6218,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,12,05,2019,18,05,23,30
4,4h 45m,1 stop,No info,13302,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,01,03,2019,16,50,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,2h 30m,non-stop,No info,4107,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,9,04,2019,19,55,22,25
10679,2h 35m,non-stop,No info,4145,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,27,04,2019,20,45,23,20
10680,3h,non-stop,No info,7229,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,27,04,2019,08,20,11,20
10681,2h 40m,non-stop,No info,12648,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,01,03,2019,11,30,14,10
10682,8h 20m,2 stops,No info,11753,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,9,05,2019,10,55,19,15

In [16]:
df['Duration_hr']=df['Duration'].str.split(' ').str[0].str.split('h').str[0] 
df['Duration_min']=df['Duration'].str.split(' ').str[1].str.split('m').str[0]
df.fillna({'Duration_min': 0}, inplace=True)

In [17]:
df.drop("Duration",axis=1,inplace=True)

In [18]:
df

,Total_Stops,Additional_Info,Price,Airline_Air Asia,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,...,Destination_New Delhi,Date,Month,Year,Dep_Hour,Dep_Min,Arr_Hour,Arr_Min,Duration_hr,Duration_min
0,non-stop,No info,3897,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,24,03,2019,22,20,01,10,2,50
1,2 stops,No info,7662,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1,05,2019,05,50,13,15,7,25
2,2 stops,No info,13882,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,9,06,2019,09,25,04,25,19,0
3,1 stop,No info,6218,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,12,05,2019,18,05,23,30,5,25
4,1 stop,No info,13302,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,01,03,2019,16,50,21,35,4,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,non-stop,No info,4107,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9,04,2019,19,55,22,25,2,30
10679,non-stop,No info,4145,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,27,04,2019,20,45,23,20,2,35
10680,non-stop,No info,7229,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,27,04,2019,08,20,11,20,3,0
10681,non-stop,No info,12648,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,01,03,2019,11,30,14,10,2,40
10682,2 stops,No info,11753,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9,05,2019,10,55,19,15,8,20

In [25]:
from sklearn.preprocessing import OrdinalEncoder

df['Total_Stops'].mode()
df['Total_Stops'].unique()
ord_encoder=OrdinalEncoder(categories=[['non-stop','1 stop','2 stops','3 stops','4 stops']])
df[['Total_Stops']]=ord_encoder.fit_transform(df[['Total_Stops']])
df.reset_index(drop=True,inplace=True)

In [ ]:
df.fillna({'Total_Stops':'1 stop'},inplace=True)
from sklearn.preprocessing import OrdinalEncoder

df['Total_Stops'].mode()
df['Total_Stops'].unique()
ord_encoder=OrdinalEncoder(categories=[['non-stop','1 stop','2 stops','3 stops','4 stops']])
df.head()
ord_encoded=ord_encoder.fit_transform(df[['Total_Stops']])
df['Total_stop']=ord_encoded
df.drop('Total_Stops',axis=1,inplace=True)

,Total_Stops,Additional_Info,Price,Airline_Air Asia,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,...,Destination_New Delhi,Date,Month,Year,Dep_Hour,Dep_Min,Arr_Hour,Arr_Min,Duration_hr,Duration_min
0,0.0,No info,3897,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,24,03,2019,22,20,01,10,2,50
1,2.0,No info,7662,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1,05,2019,05,50,13,15,7,25
2,2.0,No info,13882,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,9,06,2019,09,25,04,25,19,0
3,1.0,No info,6218,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,12,05,2019,18,05,23,30,5,25
4,1.0,No info,13302,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,01,03,2019,16,50,21,35,4,45

In [29]:
df.drop('Additional_Info',axis=1,inplace=True)

In [30]:
df.head(2)

,Total_Stops,Price,Airline_Air Asia,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,...,Destination_New Delhi,Date,Month,Year,Dep_Hour,Dep_Min,Arr_Hour,Arr_Min,Duration_hr,Duration_min
0,0.0,3897,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,24,03,2019,22,20,01,10,2,50
1,2.0,7662,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1,05,2019,05,50,13,15,7,25